version: "2"
services:
  # the database image
  db:
    image: "postgres:9.6"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: h3acatalog_dev
    ports:
      # maintenance port
      - "5432:5432"
    volumes:
      - /Users/lyee/longyee/h3acatalog/dbdata:/var/lib/postgres

  # the main image, this is the application
  web:
    restart: always
    image: web
    environment:
      PORT: "4000"
      MIX_ENV: "dev"
      DB_HOST: db
    ports:
      - "4000:4000"
    links:
      - "db"
    volumes:
      - /Users/lyee/longyee/h3acatalog/uploads:/root/h3acatalog/uploads
    depends_on:
      - db

volumes:
  # for persistance of database data
  dbdata:
    driver: local

  # for keeping uploads
  uploads:
    driver: local
